version: '2.1'
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.17'
      - run: |
              yarn
              yarn prettier 
              yarn build 
  eb-Deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          command: |
            eb deploy 
workflows:
  test_my_app:
    jobs:
      - install-node-example
      - eb-Deploy:
          requires: 
            - install-node-example
