version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs: 
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
        install-yarn: true
        node-version: '16.17'
      - run:
          name: install Packages
          command: yarn 
  printMessage: 
    - run: 
          name: Print Message
          command: echo "Everything is good"         
workflows:
  Node-workflow:
    jobs:
      - install-node
      - printMessage
